[package]
name = "YARC"
version = "0.1.0"
authors = ["Theodore L <theodoreleebrant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
sdl2 = "0.34.0"
